// WARNING: this is an autogenerated file. Any change might be overwritten!
LPCSTR ANY[] = { "", "|", NULL };
LPCSTR Multimedia[] = { "AudioVideo", "|", NULL };
LPCSTR AudioVideo[] = { "AudioVideo", "Video", "Audio", "|", NULL };
LPCSTR AudioVideoorEducation[] = { "AudioVideo", "|", "Education", "|", NULL };
LPCSTR AudioorVideoorAudioVideo[] = { "Audio", "|", "Video", "|", "AudioVideo", "|", NULL };
LPCSTR Development[] = { "Development", "|", NULL };
LPCSTR EducationComputerScienceorScienceComputerScience[] = { "Education", "ComputerScience", "|", "Science", "ComputerScience", "|", NULL };
LPCSTR EducationMathorScienceMath[] = { "Education", "Math", "|", "Science", "Math", "|", NULL };
LPCSTR EducationorScience[] = { "Education", "|", "Science", "|", NULL };
LPCSTR EducationorScienceorUtility[] = { "Education", "|", "Science", "|", "Utility", "|", NULL };
LPCSTR Game[] = { "Game", "|", NULL };
LPCSTR Graphics[] = { "Graphics", "|", NULL };
LPCSTR Graphics2DGraphics[] = { "Graphics", "2DGraphics", "|", NULL };
LPCSTR GraphicsScanning[] = { "Graphics", "Scanning", "|", NULL };
LPCSTR GraphicsorOffice[] = { "Graphics", "|", "Office", "|", NULL };
LPCSTR Network[] = { "Network", "|", NULL };
LPCSTR NetworkorAudio[] = { "Network", "|", "Audio", "|", NULL };
LPCSTR NetworkorDevelopment[] = { "Network", "|", "Development", "|", NULL };
LPCSTR Office[] = { "Office", "|", NULL };
LPCSTR OfficeorDevelopment[] = { "Office", "|", "Development", "|", NULL };
LPCSTR OfficeorDevelopmentorAudioVideo[] = { "Office", "|", "Development", "|", "AudioVideo", "|", NULL };
LPCSTR OfficeorNetwork[] = { "Office", "|", "Network", "|", NULL };
LPCSTR OfficeorTextTools[] = { "Office", "|", "TextTools", "|", NULL };
LPCSTR Settings[] = { "Settings", "|", NULL };
LPCSTR SettingsHardwareSettings[] = { "Settings", "DesktopSettings", "HardwareSettings", "|", NULL };
LPCSTR SettingsorSystem[] = { "Settings", "|", "System", "|", NULL };
LPCSTR SettingsorUtility[] = { "Settings", "|", "Utility", "|", NULL };
LPCSTR System[] = { "System", "|", NULL };
LPCSTR SystemFileTools[] = { "System", "FileTools", "|", NULL };
LPCSTR SystemorGame[] = { "System", "|", "Game", "|", NULL };
LPCSTR SystemorNetwork[] = { "System", "|", "Network", "|", NULL };
LPCSTR Utility[] = { "Utility", "|", NULL };
LPCSTR UtilityArchiving[] = { "Utility", "Archiving", "|", NULL };
LPCSTR UtilityorSystem[] = { "Utility", "|", "System", "|", NULL };

namespace spec {

tListMeta menuinfo[] =
{
// TRANSLATORS: This is a menu category name from freedesktop.org. Please add spaces as needed but no double-quotes. Context: Graphics
    { N_("Accessories"), "Utility", "folder", NULL},
    { N_("Development"), "Development", "folder", NULL},
    { N_("Education"), "Education", "folder", NULL},
    { N_("Games"), "Games", "folder", NULL},
    { N_("Graphics"), "Graphics", "folder", NULL},
    { N_("Hardware"), "Hardware", "folder", (char**) &Settings},
    { N_("Multimedia"), "AudioVideo", "folder", NULL},
    { N_("Network"), "Network", "folder", NULL},
    { N_("Office"), "Office", "folder", NULL},
    { N_("Other"), "Other", "folder", NULL},
    { N_("Personal"), "Personal", "folder", (char**) &Settings},
    { N_("Screensavers"), "Screensavers", "folder", NULL},
    { N_("Settings"), "Settings", "folder", NULL},
    { N_("System"), "System", "folder", NULL},
};
}
